server:
  port: 9051
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.9.181.164:3306/pweb
    username: root
    password: 123456
  
  mvc:
    static-path-pattern: /**
  resources: 
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存
  jpa:
    hibernate:
      ddl-auto: update
